
name: Node CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - run: yarn lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - run: yarn test
