
name: Bun CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Bun Runtime
      uses: antongolub/action-setup-bun@v1
      with:
        bun-repo: 'oven-sh/bun'
    - run: bun install
    - name: Format & Lint Check
      run: bun run lint
    - name: Tests
      run: bun run test
